// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: goods_detail.proto

package protoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoodsDataInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover        string  `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Picture      string  `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	Profile      string  `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	Prices       float64 `protobuf:"fixed64,6,opt,name=prices,proto3" json:"prices,omitempty"`
	Detail       string  `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	BusinessId   int64   `protobuf:"varint,8,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	BusinessName string  `protobuf:"bytes,9,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	State        int64   `protobuf:"varint,10,opt,name=state,proto3" json:"state,omitempty"`
	StockNum     int64   `protobuf:"varint,11,opt,name=stock_num,json=stockNum,proto3" json:"stock_num,omitempty"`
}

func (x *GoodsDataInfo) Reset() {
	*x = GoodsDataInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_detail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsDataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDataInfo) ProtoMessage() {}

func (x *GoodsDataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_detail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDataInfo.ProtoReflect.Descriptor instead.
func (*GoodsDataInfo) Descriptor() ([]byte, []int) {
	return file_goods_detail_proto_rawDescGZIP(), []int{0}
}

func (x *GoodsDataInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsDataInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GoodsDataInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *GoodsDataInfo) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *GoodsDataInfo) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *GoodsDataInfo) GetPrices() float64 {
	if x != nil {
		return x.Prices
	}
	return 0
}

func (x *GoodsDataInfo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *GoodsDataInfo) GetBusinessId() int64 {
	if x != nil {
		return x.BusinessId
	}
	return 0
}

func (x *GoodsDataInfo) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *GoodsDataInfo) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *GoodsDataInfo) GetStockNum() int64 {
	if x != nil {
		return x.StockNum
	}
	return 0
}

type GoodsDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States     int64          `protobuf:"varint,1,opt,name=states,proto3" json:"states,omitempty"`
	GoodDetail *GoodsDataInfo `protobuf:"bytes,2,opt,name=good_detail,json=goodDetail,proto3" json:"good_detail,omitempty"`
}

func (x *GoodsDetailResponse) Reset() {
	*x = GoodsDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_detail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailResponse) ProtoMessage() {}

func (x *GoodsDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_detail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailResponse.ProtoReflect.Descriptor instead.
func (*GoodsDetailResponse) Descriptor() ([]byte, []int) {
	return file_goods_detail_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsDetailResponse) GetStates() int64 {
	if x != nil {
		return x.States
	}
	return 0
}

func (x *GoodsDetailResponse) GetGoodDetail() *GoodsDataInfo {
	if x != nil {
		return x.GoodDetail
	}
	return nil
}

type GoodsDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoodsId int64 `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
}

func (x *GoodsDetailRequest) Reset() {
	*x = GoodsDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_detail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GoodsDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsDetailRequest) ProtoMessage() {}

func (x *GoodsDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_detail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsDetailRequest.ProtoReflect.Descriptor instead.
func (*GoodsDetailRequest) Descriptor() ([]byte, []int) {
	return file_goods_detail_proto_rawDescGZIP(), []int{2}
}

func (x *GoodsDetailRequest) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

var File_goods_detail_proto protoreflect.FileDescriptor

var file_goods_detail_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x22, 0xa8, 0x02, 0x0a, 0x0d, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x22, 0x6b, 0x0a,
	0x13, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0b,
	0x67, 0x6f, 0x6f, 0x64, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a,
	0x67, 0x6f, 0x6f, 0x64, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x2f, 0x0a, 0x12, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x64, 0x32, 0x61, 0x0a, 0x0b, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x6f,
	0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x2e, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_goods_detail_proto_rawDescOnce sync.Once
	file_goods_detail_proto_rawDescData = file_goods_detail_proto_rawDesc
)

func file_goods_detail_proto_rawDescGZIP() []byte {
	file_goods_detail_proto_rawDescOnce.Do(func() {
		file_goods_detail_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_detail_proto_rawDescData)
	})
	return file_goods_detail_proto_rawDescData
}

var file_goods_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_goods_detail_proto_goTypes = []interface{}{
	(*GoodsDataInfo)(nil),       // 0: goods_detail.goodsDataInfo
	(*GoodsDetailResponse)(nil), // 1: goods_detail.goodsDetailResponse
	(*GoodsDetailRequest)(nil),  // 2: goods_detail.goodsDetailRequest
}
var file_goods_detail_proto_depIdxs = []int32{
	0, // 0: goods_detail.goodsDetailResponse.good_detail:type_name -> goods_detail.goodsDataInfo
	2, // 1: goods_detail.GoodsDetail.GoodsDetail:input_type -> goods_detail.goodsDetailRequest
	1, // 2: goods_detail.GoodsDetail.GoodsDetail:output_type -> goods_detail.goodsDetailResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_goods_detail_proto_init() }
func file_goods_detail_proto_init() {
	if File_goods_detail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goods_detail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsDataInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_detail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_detail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GoodsDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_detail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_detail_proto_goTypes,
		DependencyIndexes: file_goods_detail_proto_depIdxs,
		MessageInfos:      file_goods_detail_proto_msgTypes,
	}.Build()
	File_goods_detail_proto = out.File
	file_goods_detail_proto_rawDesc = nil
	file_goods_detail_proto_goTypes = nil
	file_goods_detail_proto_depIdxs = nil
}
