// Code generated by goctl. DO NOT EDIT!
// Source: goods_detail.proto

package goodsdetail

import (
	"context"

	"github.com/reation/micro_service_goods_service/protoc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GoodsDataInfo       = protoc.GoodsDataInfo
	GoodsDetailRequest  = protoc.GoodsDetailRequest
	GoodsDetailResponse = protoc.GoodsDetailResponse

	GoodsDetail interface {
		GoodsDetail(ctx context.Context, in *GoodsDetailRequest, opts ...grpc.CallOption) (*GoodsDetailResponse, error)
	}

	defaultGoodsDetail struct {
		cli zrpc.Client
	}
)

func NewGoodsDetail(cli zrpc.Client) GoodsDetail {
	return &defaultGoodsDetail{
		cli: cli,
	}
}

func (m *defaultGoodsDetail) GoodsDetail(ctx context.Context, in *GoodsDetailRequest, opts ...grpc.CallOption) (*GoodsDetailResponse, error) {
	client := protoc.NewGoodsDetailClient(m.cli.Conn())
	return client.GoodsDetail(ctx, in, opts...)
}
