// Code generated by goctl. DO NOT EDIT!
// Source: goods_detail.proto

package server

import (
	"context"

	"github.com/reation/micro_service_goods_service/goods_detail/internal/logic"
	"github.com/reation/micro_service_goods_service/goods_detail/internal/svc"
	"github.com/reation/micro_service_goods_service/protoc"
)

type GoodsDetailServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedGoodsDetailServer
}

func NewGoodsDetailServer(svcCtx *svc.ServiceContext) *GoodsDetailServer {
	return &GoodsDetailServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsDetailServer) GoodsDetail(ctx context.Context, in *protoc.GoodsDetailRequest) (*protoc.GoodsDetailResponse, error) {
	l := logic.NewGoodsDetailLogic(ctx, s.svcCtx)
	return l.GoodsDetail(in)
}
