// Code generated by goctl. DO NOT EDIT!
// Source: goods_list.proto

package server

import (
	"context"

	"micro_service_goods_service/goods_list/internal/logic"
	"micro_service_goods_service/goods_list/internal/svc"
	"micro_service_goods_service/protoc"
)

type GoodsListServer struct {
	svcCtx *svc.ServiceContext
	protoc.UnimplementedGoodsListServer
}

func NewGoodsListServer(svcCtx *svc.ServiceContext) *GoodsListServer {
	return &GoodsListServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsListServer) GoodsList(ctx context.Context, in *protoc.GoodsListRequest) (*protoc.GoodsListResponse, error) {
	l := logic.NewGoodsListLogic(ctx, s.svcCtx)
	return l.GoodsList(in)
}
